use std::env;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

fn is_toml_theme(path: &Path) -> bool {
    path.extension().and_then(|s| s.to_str()) == Some("toml")
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let themes_dir = manifest_dir.join("themes");
    let fonts_dir = manifest_dir.join("fonts");

    println!("cargo:rerun-if-changed=themes");
    println!("cargo:rerun-if-changed=fonts");

    let mut theme_files: Vec<PathBuf> = match fs::read_dir(&themes_dir) {
        Ok(rd) => rd
            .filter_map(|e| e.ok())
            .map(|e| e.path())
            .filter(|p| p.is_file() && is_toml_theme(p))
            .collect(),
        Err(_) => Vec::new(),
    };

    theme_files.sort();

    for path in &theme_files {
        println!("cargo:rerun-if-changed={}", path.display());
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let dest_path = out_dir.join("builtin_themes.rs");

    let mut out = String::new();
    out.push_str("// @generated by build.rs\n");
    out.push_str("pub const BUILTIN_THEMES: &[(&str, &str)] = &[\n");

    let mut names: Vec<String> = Vec::new();

    for path in &theme_files {
        let file_name = path
            .file_name()
            .and_then(|s| s.to_str())
            .unwrap_or_default();
        let name = file_name.trim_end_matches(".toml");
        names.push(name.to_string());

        out.push_str("    (\"");
        out.push_str(name);
        out.push_str("\", include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/themes/");
        out.push_str(file_name);
        out.push_str("\"))),\n");
    }

    out.push_str("];\n\n");
    out.push_str("pub const BUILTIN_THEME_NAMES: &[&str] = &[\n");
    for name in &names {
        out.push_str("    \"");
        out.push_str(name);
        out.push_str("\",\n");
    }
    out.push_str("];\n");

    let mut f = fs::File::create(&dest_path).expect("create builtin_themes.rs");
    f.write_all(out.as_bytes())
        .expect("write builtin_themes.rs");
}
