[package]
name = "yatmux"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
anyhow = "1"
arboard = "2"
dirs = "5"
font8x8 = "0.3"
open = "5"
portable-pty = "0.9"
regex = "1"
serde = { version = "1", features = ["derive"] }
softbuffer = "0.4"
toml = "0.8"
tattoy-wezterm-cell = "0.1.0-1"
tattoy-wezterm-surface = "0.1.0-fork.2"
tattoy-wezterm-term = "0.1.0-fork.5"
vt100 = "0.15"
winit = "0.30"

[patch.crates-io]
tattoy-wezterm-term = { path = "vendor/tattoy-wezterm-term" }

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3
